services:
  - type: web
    name: reallike-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: USE_SQLITE
        value: False
