# Generated by Django 5.1.6 on 2026-04-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='liketask',
            new_name='tasks_liket_user_id_d82e68_idx',
            old_name='tasks_liket_user_id_07b5ae_idx',
        ),
        migrations.RenameIndex(
            model_name='liketask',
            new_name='tasks_liket_post_id_53293e_idx',
            old_name='tasks_liket_post_id_74b96e_idx',
        ),
    ]
