# Generated by Django 5.1.6 on 2026-04-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_status_b12df4_idx',
            old_name='posts_post_status_2d848c_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_owner_i_509d9f_idx',
            old_name='posts_post_owner_i_587ef5_idx',
        ),
    ]
